In [1]:
import torch
import torch.nn as nn

/system/apps/userenv/alkin/default/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
device = torch.device("cuda:6")

In [4]:
model = nn.Linear(1024, 1024)
model.to(device)
model = nn.DataParallel(model, device_ids=[6, 7])
print(model(torch.randn(32, 1024).to(device)))

tensor([[-0.0571, -0.1370, -0.2169,  ...,  0.5390, -0.1141,  0.3640],
        [ 0.5225, -0.8591,  0.5108,  ..., -0.3916,  0.4059, -0.5997],
        [ 0.0561, -0.1040,  1.0566,  ...,  0.4401,  0.3889,  0.0049],
        ...,
        [-0.4902,  0.0272, -0.4503,  ...,  0.3274,  0.8314, -0.8121],
        [ 0.7316, -0.3792, -0.3314,  ..., -0.7897,  0.5002, -0.0159],
        [ 0.3468, -0.5296, -0.1580,  ..., -1.0617, -0.5325, -1.1135]],
       device='cuda:6', grad_fn=<GatherBackward>)


In [6]:
model = nn.Linear(1024, 1024)
model.to(device)
model = nn.DataParallel(model, device_ids=[6, 7])
model.to(device)
print(model(torch.randn(32, 1024).to(device)))

tensor([[ 0.7342,  0.3100,  0.0883,  ...,  0.5354, -0.8100,  1.1021],
        [ 0.0995, -0.4837,  0.6038,  ..., -0.4872,  0.6613,  0.2326],
        [-0.2703, -0.4442,  0.5208,  ..., -0.2856, -0.6850,  0.7463],
        ...,
        [ 0.7307, -0.2227,  0.0291,  ...,  1.0768, -1.3793,  0.7948],
        [-0.6843,  0.2646,  0.3406,  ..., -0.2419,  0.7972,  0.8963],
        [-0.0560, -0.4701,  0.3845,  ..., -0.3214,  0.0804,  0.2355]],
       device='cuda:6', grad_fn=<GatherBackward>)


In [3]:
model = nn.Linear(1024, 1024)
model.to(device)
model = nn.DataParallel(model, device_ids=[6, 7])
print(model(torch.randn(32, 1024).to(device)))

tensor([[ 0.6447,  0.0745,  0.0551,  ...,  0.5613, -0.4180,  1.0456],
        [-0.2655, -0.0981, -0.9405,  ...,  0.6602, -0.0111,  0.2282],
        [-0.7912, -0.9279, -0.9875,  ...,  0.2946,  0.1081,  0.7896],
        ...,
        [ 0.8561,  0.6211,  1.1048,  ..., -1.2597,  0.8631,  0.4595],
        [ 0.7593,  0.6892, -0.1459,  ...,  0.5549, -0.1861,  0.6619],
        [-0.0624,  1.0943, -0.5189,  ..., -0.1226,  0.1904,  0.3140]],
       device='cuda:6', grad_fn=<GatherBackward>)


In [6]:
model = nn.Linear(1024, 1024)
model.to(device)
model = nn.DataParallel(model, device_ids=[6, 7])
print(model(torch.randn(32, 1024)))

tensor([[-0.1013,  0.2817, -0.3589,  ..., -0.1329, -0.1013,  0.7614],
        [-0.3360, -0.7355, -0.7325,  ..., -0.3156,  0.6271,  0.0536],
        [ 0.0157,  0.7771,  0.0379,  ..., -0.5107,  0.7133, -0.4684],
        ...,
        [-0.0770,  0.8478,  0.7259,  ..., -0.3162, -1.0318, -0.5803],
        [-0.0897, -0.7665,  0.2187,  ..., -0.1535, -0.5100,  0.5531],
        [ 0.1691, -0.5203, -0.9593,  ...,  0.5960, -0.7067, -0.2455]],
       device='cuda:6', grad_fn=<GatherBackward>)


In [7]:
model = nn.Linear(1024, 1024)
model = nn.DataParallel(model, device_ids=[6, 7])
print(model(torch.randn(32, 1024)))

RuntimeError: module must have its parameters and buffers on device cuda:6 (device_ids[0]) but found one of them on device: cpu